hw10_motion_sensor is completed
VladislavLisovenko/hw-vladl pull request #12
Opened 2023-10-29 04:56 UTC by VladislavLisovenko

## Домашнее задание №10 «Обработка данных сенсора движения»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~80 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2023-10-29 05:55 UTC, vladislavmass requested changes
Данное решение приведет к массовым паникам в коде. Правильным решением в данном случае является использование `context.WithTimeout` и передача его в функции сенсора и обработчика

2023-10-29 05:55 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +		ch <- i
Запись в закрытый канал приведет к панике, что не является нормальным завершением программы.

2023-10-29 05:55 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +			processedData <- (sum / 10)
Запись в закрытый канал приведет к панике, что не является нормальным завершением программы.

2023-10-29 05:55 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +		sum += <-ch
Закрытый канал возвращать всегда значение по умолчанию

2023-10-29 05:55 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +			break exitFor
Break exitFor в данном случае лишнее

2023-10-30 22:47 UTC, VladislavLisovenko commented on hw10_motion_sensor/main.go
> +		sum += <-ch
Здесь не понял что нужно сделать - проверить состояние канала и читать из канала только еси он не закрыт?

2023-10-31 19:29 UTC, vladislavmass requested changes

2023-10-31 19:29 UTC, hungry-honeybadger commented on hw10_motion_sensor/main.go
> +			stop = true
Тут можно сразу сделать return без всяких переводов и это будет смотреться более профессионально

2023-10-31 19:29 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +func Sensor(ctx context.Context, ch chan<- float64) {
Лучши вариантом для этой функции будет следующая сигнатура `func Sensor(ctx context.Context )chan<- float64`. Тоесть функция создает канал, возвращает его и в этой функции запускается генерирующая gorutina и в этой gorutine в блоке defer весит закрытие канала.

2023-10-31 19:29 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
Время генерации данных должно составлять 1 минуту

2023-10-31 19:29 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +			if i%10 == 0 {
Финальные данные тоже было бы не плохо вернуть

2023-11-02 12:19 UTC, vladislavmass approved these changes

2023-11-03 02:11 UTC, merged