hw15_go_sql almost ready
VladislavLisovenko/hw-vladl pull request #17
Opened 2024-01-02 15:55 UTC by VladislavLisovenko

## Домашнее задание №15 «Go-клиент для БД онлайн магазина»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)

### Критерии оценки
- [ ] Понятность и чистота кода - до 2 баллов
- [ ] Реализован слой взаимодействия с БД - 2 балла
- [ ] Используются транзакции - 2 балла
- [ ] Сервис отдает данные по HTTP - 2 балла

#### Зачёт от 6 баллов

2024-01-02 18:40 UTC, vladislavmass requested changes

2024-01-02 18:40 UTC, vladislavmass commented on hw15_go_sql/server/server.go
> +	case ActionAdd:
решение выглядит как велосипед. Как это должно работать продумано еще в спецификации http.
У нас есть несколько видов запросов.

Get используется либо для получения информации обо всех объектах одного типа или об одном объекте
Get запрос по пути /orders вернет все заказы а запрос по пути /order/[id] вернет информацию о конкретном заказе

Post используется для изменения или добавления объекта
Post запрос по пути /order добавит заказ  а запрос по пути /order/[id] изменит конкретный заказ

Put используется только для добавления объекта( применяется достаточно редко)
PUT запрос по пути /order добавит заказ

delete удалить объект
delete запрос по пути /order/[id] удалит конкретный заказ 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

2024-01-02 18:40 UTC, vladislavmass commented on hw15_go_sql/server/server.go
> +		entity, err := decodedOrder(r.Body)
не надо передавать все боди, когда нужен только id. Трафик в высоконагруженных системах стараются экономить

2024-01-02 18:40 UTC, vladislavmass commented on hw15_go_sql/server/server.go
> +	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
Не надо все вешать на 1 путь. Зарегистрируйте несколько обработчиков, которые будут использоваться для разных целей

2024-01-02 18:40 UTC, vladislavmass commented on hw15_go_sql/server/server.go
> +func decodedOrderProduct(body io.ReadCloser) (entities.OrderProducts, error) {
Делать под это метод выглядит как крайне странная история. По сути единственный вариант где нам нужен Парсинг body, это в Post запроси( ну в худшем случае в Post и Put). Так может лучше перенести этот код в обработчик POST запроса а не делать отдельный метод?

2024-01-02 18:40 UTC, vladislavmass commented on hw15_go_sql/server/server.go
> +// func decodedEntity[T Entity](body io.ReadCloser, entity T) error {
Хорошая кстати были идея сделать парсе с дженериками.

2024-01-02 18:40 UTC, vladislavmass commented on hw15_go_sql/server/db/order_products.go
> +	queryString := "update public.\"OrderProducts\" set order_id=$1, product_id=$2 where id=$3"
Запросы лучше писать в raw строках, что бы не экранировать кавычки

2024-01-02 18:40 UTC, vladislavmass commented on hw15_go_sql/server/db/order_products.go
> +	tx, err := database.BeginTx(context.Background(), nil)
А зачем тут транзакции когда у нас всего 1 запрос в ней?

2024-01-03 09:25 UTC, VladislavLisovenko commented on hw15_go_sql/server/db/order_products.go
> +	tx, err := database.BeginTx(context.Background(), nil)
Согласен, транзакция здесь не нужна, сдела для галочки, потому что в задании так сказано.

2024-01-03 09:26 UTC, VladislavLisovenko commented on hw15_go_sql/server/db/order_products.go
> +	queryString := "update public.\"OrderProducts\" set order_id=$1, product_id=$2 where id=$3"
Хорошо

2024-01-03 09:27 UTC, VladislavLisovenko commented on hw15_go_sql/server/server.go
> +// func decodedEntity[T Entity](body io.ReadCloser, entity T) error {
Не смог рабочее решение сделать

2024-01-03 09:28 UTC, VladislavLisovenko commented on hw15_go_sql/server/server.go
> +func decodedOrderProduct(body io.ReadCloser) (entities.OrderProducts, error) {
Хорошо, переделаю, просто у меня вообще нет представления как делать подобные приложения.

2024-01-03 09:30 UTC, VladislavLisovenko commented on hw15_go_sql/server/server.go
> +	case ActionAdd:
Про велосипед полностью согласен, но пока нет знаний как делать правильно.

2024-01-03 09:30 UTC, VladislavLisovenko commented on hw15_go_sql/server/server.go
> +		entity, err := decodedOrder(r.Body)
Буду знать, спасибо.

2024-01-03 09:32 UTC, VladislavLisovenko commented on hw15_go_sql/server/server.go
> +	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
Хорошо, попробую, спасибо.

2024-01-10 06:50 UTC, merged